### ISSUE TITLE
Project cmake configuration

### ISSUE THREAD

**Issue by tommasoclini** [MMlodzinski/Sunton_ESP32-8048S070c_ESP_IDF_LVGL_example#2]
How do I build all squareline studio exported files using the generated CmakeLists.txt(it adds a library with all source files)? This way, I don't have to edit main/CmakeLists.txt every time I add a screen or something like that.

**Comment by MMlodzinski** [comment]
Try including that generated CMakeLists.txt in main/CMakeLists.txt. As far as I know including it should run its code. To do that in main/CMakeLists.txt type:
include(path/to/your/CMakeLists.txt)
Then in idf_component_register command replace hard-coded sources with your given sources from the new CMakeLists.txt.

Hope that will work, as I didn't test it.

Sorry for my late response, I didn't see the notification about that issue.

**Comment by tommasoclini** [comment]
I've got an example for the board with more recent versions of libraries, esp lvgl port to make things simpler and better and a simple bsp header, because of the many stars of this repo, outdated libraries, and "from scratch" way of handling lvgl, can I create a pull request to replace it?
I've tested with latest version of everything(esp-idf 5.3.1, lvgl 9.2, and latest version of drivers and lv_esp32_port).
[my repo](https://github.com/tommasoclini/esp32-8048s070-example)
I plan on adding instructions on how to add squareline studio generated code, but for now, the example runs the widgets demo.

**Comment by MMlodzinski** [comment]
Well, yes you can create pull request, but make sure everything works fine - I can't test anything, because I don't have access to the devboard anymore (that's the reason I didn't work on this project anymore). I hope new versions will help people with their projects!

**Comment by tommasoclini** [comment]
I have the devboard with me, everything works fine, I'm getting 10 to 30 fps on the widgets example depending on the thing that it's doing, by tomorrow I'll create a pull request
